// This source file was generated by Unified Inventory CodeGen, Please DO NOT modify this file.
package com.setar.uiv.model.product;

import com.fasterxml.jackson.annotation.JsonFilter;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonView;
import com.nokia.nsw.uiv.jackson.UivJsonViews;
import com.nokia.nsw.uiv.model.service.Service;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.neo4j.ogm.annotation.NodeEntity;
import org.neo4j.ogm.annotation.Relationship;

@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        defaultImpl = com.setar.uiv.model.product.CustomerFacingService.class,
        include = JsonTypeInfo.As.EXISTING_PROPERTY,
        visible = true,
        property = "@type"
)
@JsonFilter("com.setar.uiv.model.product.CustomerFacingService")
@NodeEntity(
        label = "com.setar.uiv.model.product.CustomerFacingService"
)
@Slf4j
public class CustomerFacingService extends Service {
    @JsonView({
            UivJsonViews.WriteView.class,
            UivJsonViews.ReadView.class
    })
    public String catalogItemName;

    @JsonView({
            UivJsonViews.WriteView.class,
            UivJsonViews.ReadView.class
    })
    public String catalogItemVersion;

    @JsonView({
            UivJsonViews.WriteView.class,
            UivJsonViews.ReadView.class
    })
    public String transactionId;

    @JsonView({
            UivJsonViews.WriteView.class,
            UivJsonViews.ReadView.class
    })
    public String transactionType;

    @JsonFilter("containingProduct")
    @Relationship(
            type = "CONTAINS",
            direction = "INCOMING"
    )
    @Schema(
            type = "com.setar.uiv.model.product.Product",
            implementation = String.class,
            allowableValues = "{com.setar.uiv.model.product.Product}"
    )
    protected Product containingProduct;

    @JsonFilter("containedRfs")
    @Relationship(
            type = "CONTAINS",
            direction = "OUTGOING"
    )
    @Schema(
            type = "java.util.Set<com.setar.uiv.model.product.ResourceFacingService>",
            implementation = String.class,
            allowableValues = "[com.setar.uiv.model.product.ResourceFacingService]"
    )
    protected Set<ResourceFacingService> containedRfs = new HashSet<>();

    public String getCatalogItemName() {
        return this.catalogItemName;
    }

    public void setCatalogItemName(String catalogItemName) {
        if ((catalogItemName==null && this.catalogItemName!=null) || (catalogItemName != null && !catalogItemName.equals(this.catalogItemName))) {
            this.setModified(true);
        }
        this.catalogItemName=catalogItemName;
    }

    public String getCatalogItemVersion() {
        return this.catalogItemVersion;
    }

    public void setCatalogItemVersion(String catalogItemVersion) {
        if ((catalogItemVersion==null && this.catalogItemVersion!=null) || (catalogItemVersion != null && !catalogItemVersion.equals(this.catalogItemVersion))) {
            this.setModified(true);
        }
        this.catalogItemVersion=catalogItemVersion;
    }

    public String getTransactionId() {
        return this.transactionId;
    }

    public void setTransactionId(String transactionId) {
        if ((transactionId==null && this.transactionId!=null) || (transactionId != null && !transactionId.equals(this.transactionId))) {
            this.setModified(true);
        }
        this.transactionId=transactionId;
    }

    public String getTransactionType() {
        return this.transactionType;
    }

    public void setTransactionType(String transactionType) {
        if ((transactionType==null && this.transactionType!=null) || (transactionType != null && !transactionType.equals(this.transactionType))) {
            this.setModified(true);
        }
        this.transactionType=transactionType;
    }

    @Override
    public boolean equals(Object otherObj) {
        if (this == otherObj) return true;
        if (!(otherObj instanceof CustomerFacingService)) return false;
        CustomerFacingService other = (CustomerFacingService) otherObj;
        if (null != this.getUuid() && this.getUuid().equals(other.getUuid())) {
            return true;
        }
        return new EqualsBuilder().append(this.catalogItemName, other.catalogItemName)
                .append(this.catalogItemVersion, other.catalogItemVersion)
                .append(this.transactionId, other.transactionId)
                .append(this.transactionType, other.transactionType)
                .isEquals() && super.equals(otherObj);
    }

    @Override
    public int hashCode() {
        if (null != this.getUuid()) {
            return new HashCodeBuilder(17, 37).append(this.getUuid()).toHashCode();
        }
        return new HashCodeBuilder(17,37).append(catalogItemName)
                .append(catalogItemVersion)
                .append(transactionId)
                .append(transactionType)
                .appendSuper(super.hashCode()).toHashCode();
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this).append("catalogItemName", this.catalogItemName)
                .append("catalogItemVersion", this.catalogItemVersion)
                .append("transactionId", this.transactionId)
                .append("transactionType", this.transactionType)
                .toString();
    }

    public Product getContainingProduct() {
        return this.containingProduct;
    }

    public void setContainingProduct(Product containingProduct) {
        this.setAssocModified(true);
        if (null == containingProduct && null != this.containingProduct && null != this.containingProduct.getContainedCfs()) {
            this.containingProduct.getContainedCfs().remove(this);
        }
        this.containingProduct=containingProduct;
        if (null != containingProduct && (null == containingProduct.getContainedCfs() || !containingProduct.getContainedCfs().contains(this))) {
            this.set_type(this.get_type());
            if (null == containingProduct.getContainedCfs()) {
                containingProduct.setContainedCfs(new HashSet<>());
            }
            containingProduct.addContainedCfs(this);
        }
    }

    public void addContainedRfs(ResourceFacingService element) {
        this.setAssocModified(true);
        this.containedRfs.add(element);
        if (null != element && (null == element.getContainingCfs() || !element.getContainingCfs().equals(this))) {
            this.set_type(this.get_type());
            element.setContainingCfs(this);
        }
    }

    public void removeContainedRfs(ResourceFacingService element) {
        this.setAssocModified(true);
        if (null != element && null != this.containedRfs  && this.containedRfs.remove(element) && null != element.getContainingCfs()) {
            element.setContainingCfs(null);
        }
    }

    public Set<ResourceFacingService> getContainedRfs() {
        return this.containedRfs;
    }

    public void setContainedRfs(Set<ResourceFacingService> containedRfs) {
        this.setAssocModified(true);
        if (null != this.containedRfs) {
            List<ResourceFacingService> toDelete = new ArrayList<>(this.containedRfs);
            boolean setToNull = null == containedRfs || containedRfs.isEmpty();
            if (!setToNull)  {
                toDelete.removeAll(containedRfs);
            }
            for (ResourceFacingService each : toDelete) {
                each.setContainingCfs(null);
            }
        }
        this.containedRfs=containedRfs;
        if (null != containedRfs) {
            for (ResourceFacingService each: containedRfs) {
                if (null != each && ( null == each.getContainingCfs() || !each.getContainingCfs().equals(this))) {
                    this.set_type(this.get_type());
                    each.setContainingCfs(this);
                }
            }
        }
    }
}
