// This source file was generated by Unified Inventory CodeGen, Please DO NOT modify this file.
package com.nokia.nsw.uiv.numbermanagement;

import javax.xml.bind.annotation.XmlType;

@XmlType(
        name = "com.nokia.nsw.uiv.numbermanagement.IdentifierState"
)
public enum IdentifierState {
    FREE,

    RESERVED,

    ASSIGNED,

    QUARANTINED,

    DISABLED
}
