// This source file was generated by Unified Inventory CodeGen, Please DO NOT modify this file.
package com.nokia.nsw.uiv.numbermanagement;

import javax.xml.bind.annotation.XmlType;

@XmlType(
        name = "com.nokia.nsw.uiv.numbermanagement.PoolState"
)
public enum PoolState {
    ENABLED,

    DISABLED
}
