// This source file was generated by Unified Inventory CodeGen, Please DO NOT modify this file.
package com.nokia.nsw.uiv.numbermanagement;

import jakarta.xml.bind.annotation.XmlType;

@XmlType(
        name = "PoolState",
        namespace = "com.nokia.nsw.uiv.numbermanagement"
)
public enum PoolState {
    ENABLED,

    DISABLED
}
