// This source file was generated by Unified Inventory CodeGen, Please DO NOT modify this file.
package com.nokia.nsw.uiv.model.location;

import com.fasterxml.jackson.annotation.JsonFilter;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import lombok.extern.slf4j.Slf4j;
import org.neo4j.ogm.annotation.NodeEntity;

@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        defaultImpl = com.nokia.nsw.uiv.model.location.GeographicArea.class,
        include = JsonTypeInfo.As.EXISTING_PROPERTY,
        visible = true,
        property = "@type"
)
@JsonSubTypes({
        @JsonSubTypes.Type(value = com.nokia.nsw.uiv.model.location.GeographicArea.class, name = "geographicArea"),
        @JsonSubTypes.Type(value = com.nokia.nsw.uiv.model.location.Property.class, name = "property"),
        @JsonSubTypes.Type(value = com.nokia.nsw.uiv.model.location.Space.class, name = "space")
})
@JsonFilter("com.nokia.nsw.uiv.model.location.GeographicLocation")
@NodeEntity(
        label = "com.nokia.nsw.uiv.model.location.GeographicLocation"
)
@Slf4j
public abstract class GeographicLocation extends Place {
}
