// This source file was generated by Unified Inventory CodeGen, Please DO NOT modify this file.
package com.nokia.nsw.uiv.model.location;

import javax.xml.bind.annotation.XmlType;

@XmlType(
        name = "com.nokia.nsw.uiv.model.location.GeographicSiteStatus"
)
public enum GeographicSiteStatus {
    Planned,

    Active,

    Inactive,

    Obsolete
}
