// This source file was generated by Unified Inventory CodeGen, Please DO NOT modify this file.
package com.nokia.nsw.uiv.model.location;

import jakarta.xml.bind.annotation.XmlType;

@XmlType(
        name = "GeographicSiteStatus",
        namespace = "com.nokia.nsw.uiv.model.location"
)
public enum GeographicSiteStatus {
    Planned,

    Active,

    Inactive,

    Obsolete
}
