// This source file was generated by Unified Inventory CodeGen, Please DO NOT modify this file.
package com.nokia.nsw.uiv.model.location;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import org.neo4j.ogm.typeconversion.CompositeAttributeConverter;

public class GeographicSubAddressConverter implements CompositeAttributeConverter<GeographicSubAddress> {
    @Override
    public Map<String, ?> toGraphProperties(GeographicSubAddress value) {
        if (value == null) {
            return Collections.emptyMap();
        }
        Map<String, Object> properties = new HashMap<>();
        properties.put("geographicSubAddress.subUnitType", value.getSubUnitType());
        properties.put("geographicSubAddress.subUnitNr", value.getSubUnitNr());
        properties.put("geographicSubAddress.levelType", value.getLevelType());
        properties.put("geographicSubAddress.levelNr", value.getLevelNr());
        properties.put("geographicSubAddress.buildingName", value.getBuildingName());
        properties.put("geographicSubAddress.privateStreetName", value.getPrivateStreetName());
        return properties;
    }

    @Override
    public GeographicSubAddress toEntityAttribute(Map<String, ?> value) {
        if (value == null || value.isEmpty()) {
            return null;
        }
        if ( value.get("geographicSubAddress.subUnitType") == null && value.get("geographicSubAddress.subUnitNr") == null && value.get("geographicSubAddress.levelType") == null && value.get("geographicSubAddress.levelNr") == null && value.get("geographicSubAddress.buildingName") == null && value.get("geographicSubAddress.privateStreetName") == null ) {
            return null;
        }
        GeographicSubAddress geographicSubAddress = new GeographicSubAddress();
        geographicSubAddress.setSubUnitType((String) value.get("geographicSubAddress.subUnitType"));
        geographicSubAddress.setSubUnitNr((String) value.get("geographicSubAddress.subUnitNr"));
        geographicSubAddress.setLevelType((String) value.get("geographicSubAddress.levelType"));
        geographicSubAddress.setLevelNr((String) value.get("geographicSubAddress.levelNr"));
        geographicSubAddress.setBuildingName((String) value.get("geographicSubAddress.buildingName"));
        geographicSubAddress.setPrivateStreetName((String) value.get("geographicSubAddress.privateStreetName"));
        geographicSubAddress.setModified(false);
        return geographicSubAddress;
    }
}
