// This source file was generated by Unified Inventory CodeGen, Please DO NOT modify this file.
package com.nokia.nsw.uiv.model.location;

import com.fasterxml.jackson.annotation.JsonFilter;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.nokia.nsw.uiv.datatype.Neo4jDomainNodeObject;
import com.nokia.nsw.uiv.framework.repository.annotation.Composite;
import lombok.extern.slf4j.Slf4j;
import org.neo4j.ogm.annotation.NodeEntity;

@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        defaultImpl = com.nokia.nsw.uiv.model.location.Polygon.class,
        include = JsonTypeInfo.As.EXISTING_PROPERTY,
        visible = true,
        property = "@type"
)
@JsonSubTypes({
        @JsonSubTypes.Type(value = com.nokia.nsw.uiv.model.location.Polygon.class, name = "polygon"),
        @JsonSubTypes.Type(value = com.nokia.nsw.uiv.model.location.GeographicPoint.class, name = "geographicPoint")
})
@JsonFilter("com.nokia.nsw.uiv.model.location.Geometry")
@NodeEntity(
        label = "com.nokia.nsw.uiv.model.location.Geometry"
)
@Slf4j
@Composite(
        type = Composite.Type.CHILD,
        otherEnd = "geometry",
        otherEndType = "com.nokia.nsw.uiv.model.location.Place"
)
public abstract class Geometry extends Neo4jDomainNodeObject {
}
