// This source file was generated by Unified Inventory CodeGen, Please DO NOT modify this file.
package com.nokia.nsw.uiv.model.location;

import com.fasterxml.jackson.annotation.JsonFilter;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonView;
import com.nokia.nsw.uiv.constants.FeatureFlag;
import com.nokia.nsw.uiv.datatype.SchemaSpecification;
import com.nokia.nsw.uiv.exception.ModificationNotAllowedException;
import com.nokia.nsw.uiv.framework.context.UivSpringContextAware;
import com.nokia.nsw.uiv.jackson.UivJsonViews;
import jakarta.validation.Valid;
import lombok.extern.slf4j.Slf4j;
import org.neo4j.ogm.annotation.NodeEntity;
import org.neo4j.ogm.annotation.Transient;

@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        defaultImpl = com.nokia.nsw.uiv.model.location.Property.class,
        include = JsonTypeInfo.As.EXISTING_PROPERTY,
        visible = true,
        property = "@type"
)
@JsonFilter("com.nokia.nsw.uiv.model.location.Property")
@NodeEntity(
        label = "com.nokia.nsw.uiv.model.location.Property"
)
@Slf4j
public class Property extends GeographicLocation {
    @JsonView(UivJsonViews.TmfView.class)
    @Transient
    @Valid
    private SchemaSpecification propertySpecification;

    public SchemaSpecification getPropertySpecification() {
        FeatureFlag featureFlag = UivSpringContextAware.getApplicationContext().getBean(FeatureFlag.class);
        if (this.getKind() != null && Boolean.parseBoolean(featureFlag.getTmfEnabled())) {
            this.propertySpecification = new SchemaSpecification();
            this.propertySpecification.setId(this.getKind());
            this.propertySpecification.setName(this.getKind());
            this.propertySpecification.setReferredType(this.getKind());
            this.propertySpecification.setVersion(this.getSchemaVersion());
        }
        return this.propertySpecification;
    }

    public void setPropertySpecification(SchemaSpecification propertySpecification) throws
            ModificationNotAllowedException {
        FeatureFlag featureFlag = UivSpringContextAware.getApplicationContext().getBean(FeatureFlag.class);
        if (Boolean.parseBoolean(featureFlag.getTmfEnabled())) {
            if (null != propertySpecification && null != propertySpecification.getId()) {
                if(null == this.getKind()) {
                    this.setSpecification(propertySpecification);
                    this.setKind(propertySpecification.getId());
                }
                else if (!this.getKind().equals(propertySpecification.getId())) {
                    throw new ModificationNotAllowedException("propertySpecification modification not allowed");
                }
            }
            this.propertySpecification = propertySpecification;
        }
    }
}
