// This source file was generated by Unified Inventory CodeGen, Please DO NOT modify this file.
package com.nokia.nsw.uiv.model.resource.infra.physical;

import com.fasterxml.jackson.annotation.JsonFilter;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonView;
import com.nokia.nsw.uiv.constants.FeatureFlag;
import com.nokia.nsw.uiv.datatype.SchemaSpecification;
import com.nokia.nsw.uiv.exception.ModificationNotAllowedException;
import com.nokia.nsw.uiv.framework.context.UivSpringContextAware;
import com.nokia.nsw.uiv.jackson.UivJsonViews;
import com.nokia.nsw.uiv.model.resource.infra.InfraDevice;
import jakarta.validation.Valid;
import lombok.extern.slf4j.Slf4j;
import org.neo4j.ogm.annotation.NodeEntity;
import org.neo4j.ogm.annotation.Transient;

@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        defaultImpl = com.nokia.nsw.uiv.model.resource.infra.physical.PhysicalDevice.class,
        include = JsonTypeInfo.As.EXISTING_PROPERTY,
        visible = true,
        property = "@type"
)
@JsonFilter("com.nokia.nsw.uiv.model.resource.infra.physical.PhysicalDevice")
@NodeEntity(
        label = "com.nokia.nsw.uiv.model.resource.infra.physical.PhysicalDevice"
)
@Slf4j
public class PhysicalDevice extends InfraDevice {
    @JsonView(UivJsonViews.TmfView.class)
    @Transient
    @Valid
    private SchemaSpecification physicalDeviceSpecification;

    public SchemaSpecification getPhysicalDeviceSpecification() {
        FeatureFlag featureFlag = UivSpringContextAware.getApplicationContext().getBean(FeatureFlag.class);
        if (this.getKind() != null && Boolean.parseBoolean(featureFlag.getTmfEnabled())) {
            this.physicalDeviceSpecification = new SchemaSpecification();
            this.physicalDeviceSpecification.setId(this.getKind());
            this.physicalDeviceSpecification.setName(this.getKind());
            this.physicalDeviceSpecification.setReferredType(this.getKind());
            this.physicalDeviceSpecification.setVersion(this.getSchemaVersion());
        }
        return this.physicalDeviceSpecification;
    }

    public void setPhysicalDeviceSpecification(SchemaSpecification physicalDeviceSpecification)
            throws ModificationNotAllowedException {
        FeatureFlag featureFlag = UivSpringContextAware.getApplicationContext().getBean(FeatureFlag.class);
        if (Boolean.parseBoolean(featureFlag.getTmfEnabled())) {
            if (null != physicalDeviceSpecification && null != physicalDeviceSpecification.getId()) {
                if(null == this.getKind()) {
                    this.setSpecification(physicalDeviceSpecification);
                    this.setKind(physicalDeviceSpecification.getId());
                }
                else if (!this.getKind().equals(physicalDeviceSpecification.getId())) {
                    throw new ModificationNotAllowedException("physicalDeviceSpecification modification not allowed");
                }
            }
            this.physicalDeviceSpecification = physicalDeviceSpecification;
        }
    }
}
