// This source file was generated by Unified Inventory CodeGen, Please DO NOT modify this file.
package com.nokia.nsw.uiv.model.resource.infra.physical;

import jakarta.xml.bind.annotation.XmlType;

@XmlType(
        name = "PhysicalLinkType",
        namespace = "com.nokia.nsw.uiv.model.resource.infra.physical"
)
public enum PhysicalLinkType {
    Unknown,

    Wireless,

    Cat4,

    Cat5,

    Cat6,

    Cat7,

    Coaxial50,

    Coaxial75,

    Coaxial100,

    FiberOptic,

    UTP,

    STP,

    RibbonCable,

    Twinaxial,

    Optical9,

    Optical50,

    Optical62,

    Other
}
