// This source file was generated by Unified Inventory CodeGen, Please DO NOT modify this file.
package com.nokia.nsw.uiv.model.resource.infra.physical;

import jakarta.xml.bind.annotation.XmlType;

@XmlType(
        name = "PhysicalPortInterfaceType",
        namespace = "com.nokia.nsw.uiv.model.resource.infra.physical"
)
public enum PhysicalPortInterfaceType {
    Unknown,

    BaseT10,

    BaseT100,

    BaseT10_100,

    BaseT1000,

    BaseT10000,

    DS0,

    DS1,

    DS3,

    OC3,

    OC12,

    OC48,

    OC192,

    Other
}
