// This source file was generated by Unified Inventory CodeGen, Please DO NOT modify this file.
package com.nokia.nsw.uiv.model.resource.logical;

import com.fasterxml.jackson.annotation.JsonFilter;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonView;
import com.nokia.nsw.uiv.constants.FeatureFlag;
import com.nokia.nsw.uiv.datatype.SchemaSpecification;
import com.nokia.nsw.uiv.exception.ModificationNotAllowedException;
import com.nokia.nsw.uiv.framework.context.UivSpringContextAware;
import com.nokia.nsw.uiv.framework.repository.annotation.Composite;
import com.nokia.nsw.uiv.jackson.UivJsonViews;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import lombok.extern.slf4j.Slf4j;
import org.neo4j.ogm.annotation.NodeEntity;
import org.neo4j.ogm.annotation.Relationship;
import org.neo4j.ogm.annotation.Transient;

@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        defaultImpl = com.nokia.nsw.uiv.model.resource.logical.Configuration.class,
        include = JsonTypeInfo.As.EXISTING_PROPERTY,
        visible = true,
        property = "@type"
)
@JsonFilter("com.nokia.nsw.uiv.model.resource.logical.Configuration")
@NodeEntity(
        label = "com.nokia.nsw.uiv.model.resource.logical.Configuration"
)
@Slf4j
@Composite(
        type = Composite.Type.CHILD,
        otherEnd = "associatedConfiguration",
        otherEndType = "com.nokia.nsw.uiv.model.resource.logical.Configuration"
)
public class Configuration extends LogicalResource {
    @JsonView(UivJsonViews.TmfView.class)
    @Transient
    @Valid
    private SchemaSpecification configurationSpecification;

    @JsonFilter("logicalResource")
    @Relationship(
            type = "HAS",
            direction = "INCOMING"
    )
    @Schema(
            type = "com.nokia.nsw.uiv.model.resource.logical.LogicalResource",
            implementation = String.class,
            allowableValues = "{com.nokia.nsw.uiv.model.resource.logical.LogicalResource}"
    )
    protected LogicalResource logicalResource;

    @JsonFilter("containing")
    @Relationship(
            type = "CONTAINS",
            direction = "INCOMING"
    )
    @Schema(
            type = "com.nokia.nsw.uiv.model.resource.logical.Configuration",
            implementation = String.class,
            allowableValues = "{com.nokia.nsw.uiv.model.resource.logical.Configuration}"
    )
    protected Configuration containing;

    @JsonFilter("contained")
    @Relationship(
            type = "CONTAINS",
            direction = "OUTGOING"
    )
    @Schema(
            type = "java.util.Set<com.nokia.nsw.uiv.model.resource.logical.Configuration>",
            implementation = String.class,
            allowableValues = "[com.nokia.nsw.uiv.model.resource.logical.Configuration]"
    )
    protected Set<Configuration> contained = new HashSet<>();

    @JsonFilter("associatedConfiguration")
    @Relationship(
            type = "ASSOCIATES_TO",
            direction = "OUTGOING"
    )
    @Schema(
            type = "java.util.Set<com.nokia.nsw.uiv.model.resource.logical.Configuration>",
            implementation = String.class,
            allowableValues = "[com.nokia.nsw.uiv.model.resource.logical.Configuration]"
    )
    protected Set<Configuration> associatedConfiguration = new HashSet<>();

    @JsonFilter("templatedLogicalResource")
    @Relationship(
            type = "HAS_TEMPLATE",
            direction = "INCOMING"
    )
    @Schema(
            type = "com.nokia.nsw.uiv.model.resource.logical.LogicalResource",
            implementation = String.class,
            allowableValues = "{com.nokia.nsw.uiv.model.resource.logical.LogicalResource}"
    )
    protected LogicalResource templatedLogicalResource;

    public SchemaSpecification getConfigurationSpecification() {
        FeatureFlag featureFlag = UivSpringContextAware.getApplicationContext().getBean(FeatureFlag.class);
        if (this.getKind() != null && Boolean.parseBoolean(featureFlag.getTmfEnabled())) {
            this.configurationSpecification = new SchemaSpecification();
            this.configurationSpecification.setId(this.getKind());
            this.configurationSpecification.setName(this.getKind());
            this.configurationSpecification.setReferredType(this.getKind());
            this.configurationSpecification.setVersion(this.getSchemaVersion());
        }
        return this.configurationSpecification;
    }

    public void setConfigurationSpecification(SchemaSpecification configurationSpecification) throws
            ModificationNotAllowedException {
        FeatureFlag featureFlag = UivSpringContextAware.getApplicationContext().getBean(FeatureFlag.class);
        if (Boolean.parseBoolean(featureFlag.getTmfEnabled())) {
            if (null != configurationSpecification && null != configurationSpecification.getId()) {
                if(null == this.getKind()) {
                    this.setSpecification(configurationSpecification);
                    this.setKind(configurationSpecification.getId());
                }
                else if (!this.getKind().equals(configurationSpecification.getId())) {
                    throw new ModificationNotAllowedException("configurationSpecification modification not allowed");
                }
            }
            this.configurationSpecification = configurationSpecification;
        }
    }

    public LogicalResource getLogicalResource() {
        return this.logicalResource;
    }

    public void setLogicalResource(LogicalResource logicalResource) {
        this.setAssocModified(true);
        if (null == logicalResource && null != this.logicalResource && null != this.logicalResource.getConfiguration()) {
            this.logicalResource.getConfiguration().remove(this);
        }
        this.logicalResource=logicalResource;
        if (null != logicalResource && (null == logicalResource.getConfiguration() || !logicalResource.getConfiguration().contains(this))) {
            this.set_type(this.get_type());
            if (null == logicalResource.getConfiguration()) {
                logicalResource.setConfiguration(new HashSet<>());
            }
            logicalResource.addConfiguration(this);
        }
    }

    public Configuration getContaining() {
        return this.containing;
    }

    public void setContaining(Configuration containing) {
        this.setAssocModified(true);
        if (null == containing && null != this.containing && null != this.containing.getContained()) {
            this.containing.getContained().remove(this);
        }
        this.containing=containing;
        if (null != containing && (null == containing.getContained() || !containing.getContained().contains(this))) {
            this.set_type(this.get_type());
            if (null == containing.getContained()) {
                containing.setContained(new HashSet<>());
            }
            containing.addContained(this);
        }
    }

    public void addContained(Configuration element) {
        this.setAssocModified(true);
        this.contained.add(element);
        if (null != element && (null == element.getContaining() || !element.getContaining().equals(this))) {
            this.set_type(this.get_type());
            element.setContaining(this);
        }
    }

    public void removeContained(Configuration element) {
        this.setAssocModified(true);
        if (null != element && null != this.contained  && this.contained.remove(element) && null != element.getContaining()) {
            element.setContaining(null);
        }
    }

    public Set<Configuration> getContained() {
        return this.contained;
    }

    public void setContained(Set<Configuration> contained) {
        this.setAssocModified(true);
        if (null != this.contained) {
            List<Configuration> toDelete = new ArrayList<>(this.contained);
            boolean setToNull = null == contained || contained.isEmpty();
            if (!setToNull)  {
                toDelete.removeAll(contained);
            }
            for (Configuration each : toDelete) {
                each.setContaining(null);
            }
        }
        this.contained=contained;
        if (null != contained) {
            for (Configuration each: contained) {
                if (null != each && ( null == each.getContaining() || !each.getContaining().equals(this))) {
                    this.set_type(this.get_type());
                    each.setContaining(this);
                }
            }
        }
    }

    public void addAssociatedConfiguration(Configuration element) {
        this.setAssocModified(true);
        this.associatedConfiguration.add(element);
    }

    public void removeAssociatedConfiguration(Configuration element) {
        this.setAssocModified(true);
        this.associatedConfiguration.remove(element);
    }

    public Set<Configuration> getAssociatedConfiguration() {
        return this.associatedConfiguration;
    }

    public void setAssociatedConfiguration(Set<Configuration> associatedConfiguration) {
        this.setAssocModified(true);
        this.associatedConfiguration=associatedConfiguration;
    }

    public LogicalResource getTemplatedLogicalResource() {
        return this.templatedLogicalResource;
    }

    public void setTemplatedLogicalResource(LogicalResource templatedLogicalResource) {
        this.setAssocModified(true);
        if (null == templatedLogicalResource && null != this.templatedLogicalResource && null != this.templatedLogicalResource.getTemplateConfiguration()) {
            this.templatedLogicalResource.getTemplateConfiguration().remove(this);
        }
        this.templatedLogicalResource=templatedLogicalResource;
        if (null != templatedLogicalResource && (null == templatedLogicalResource.getTemplateConfiguration() || !templatedLogicalResource.getTemplateConfiguration().contains(this))) {
            this.set_type(this.get_type());
            if (null == templatedLogicalResource.getTemplateConfiguration()) {
                templatedLogicalResource.setTemplateConfiguration(new HashSet<>());
            }
            templatedLogicalResource.addTemplateConfiguration(this);
        }
    }
}
