// This source file was generated by Unified Inventory CodeGen, Please DO NOT modify this file.
package com.nokia.nsw.uiv.model.resource.logical;

import com.fasterxml.jackson.annotation.JsonFilter;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.HashSet;
import java.util.Set;
import lombok.extern.slf4j.Slf4j;
import org.neo4j.ogm.annotation.NodeEntity;
import org.neo4j.ogm.annotation.Relationship;

@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        defaultImpl = com.nokia.nsw.uiv.model.resource.logical.LogicalInterface.class,
        include = JsonTypeInfo.As.EXISTING_PROPERTY,
        visible = true,
        property = "@type"
)
@JsonFilter("com.nokia.nsw.uiv.model.resource.logical.LogicalInterface")
@NodeEntity(
        label = "com.nokia.nsw.uiv.model.resource.logical.LogicalInterface"
)
@Slf4j
public class LogicalInterface extends LogicalComponent {
    @JsonFilter("owningPipe")
    @Relationship(
            type = "OWNS",
            direction = "INCOMING"
    )
    @Schema(
            type = "com.nokia.nsw.uiv.model.resource.logical.Pipe",
            implementation = String.class,
            allowableValues = "{com.nokia.nsw.uiv.model.resource.logical.Pipe}"
    )
    protected Pipe owningPipe;

    @JsonFilter("protocol")
    @Relationship(
            type = "IMPLEMENTS",
            direction = "OUTGOING"
    )
    @Schema(
            type = "java.util.Set<com.nokia.nsw.uiv.model.resource.logical.Protocol>",
            implementation = String.class,
            allowableValues = "[com.nokia.nsw.uiv.model.resource.logical.Protocol]"
    )
    protected Set<Protocol> protocol = new HashSet<>();

    public Pipe getOwningPipe() {
        return this.owningPipe;
    }

    public void setOwningPipe(Pipe owningPipe) {
        this.setAssocModified(true);
        if (null == owningPipe && null != this.owningPipe && null != this.owningPipe.getOwnedLogicalInterface()) {
            this.owningPipe.getOwnedLogicalInterface().remove(this);
        }
        this.owningPipe=owningPipe;
        if (null != owningPipe && (null == owningPipe.getOwnedLogicalInterface() || !owningPipe.getOwnedLogicalInterface().contains(this))) {
            this.set_type(this.get_type());
            if (null == owningPipe.getOwnedLogicalInterface()) {
                owningPipe.setOwnedLogicalInterface(new HashSet<>());
            }
            owningPipe.addOwnedLogicalInterface(this);
        }
    }

    public void addProtocol(Protocol element) {
        this.setAssocModified(true);
        this.protocol.add(element);
    }

    public void removeProtocol(Protocol element) {
        this.setAssocModified(true);
        this.protocol.remove(element);
    }

    public Set<Protocol> getProtocol() {
        return this.protocol;
    }

    public void setProtocol(Set<Protocol> protocol) {
        this.setAssocModified(true);
        this.protocol=protocol;
    }
}
