// This source file was generated by Unified Inventory CodeGen, Please DO NOT modify this file.
package com.nokia.nsw.uiv.model.resource;

import jakarta.xml.bind.annotation.XmlType;

@XmlType(
        name = "AdministrativeState",
        namespace = "com.nokia.nsw.uiv.model.resource"
)
public enum AdministrativeState {
    Unknown,

    Activated,

    Deactivated,

    NotApplicable
}
