// This source file was generated by Unified Inventory CodeGen, Please DO NOT modify this file.
package com.nokia.nsw.uiv.model.resource;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import org.neo4j.ogm.typeconversion.CompositeAttributeConverter;

public class OperatingSystemConverter implements CompositeAttributeConverter<OperatingSystem> {
    @Override
    public Map<String, ?> toGraphProperties(OperatingSystem value) {
        if (value == null) {
            return Collections.emptyMap();
        }
        Map<String, Object> properties = new HashMap<>();
        properties.put("operatingSystem.name", value.getName());
        properties.put("operatingSystem.version", value.getVersion());
        return properties;
    }

    @Override
    public OperatingSystem toEntityAttribute(Map<String, ?> value) {
        if (value == null || value.isEmpty()) {
            return null;
        }
        if ( value.get("operatingSystem.name") == null && value.get("operatingSystem.version") == null ) {
            return null;
        }
        OperatingSystem operatingSystem = new OperatingSystem();
        operatingSystem.setName((String) value.get("operatingSystem.name"));
        operatingSystem.setVersion((String) value.get("operatingSystem.version"));
        operatingSystem.setModified(false);
        return operatingSystem;
    }
}
