// This source file was generated by Unified Inventory CodeGen, Please DO NOT modify this file.
package com.nokia.nsw.uiv.model.resource;

import javax.xml.bind.annotation.XmlType;

@XmlType(
        name = "com.nokia.nsw.uiv.model.resource.ProtectionAssociationType"
)
public enum ProtectionAssociationType {
    Anyof,

    OneOf,

    AllOf
}
