// This source file was generated by Unified Inventory CodeGen, Please DO NOT modify this file.
package com.nokia.nsw.uiv.model.resource;

import jakarta.xml.bind.annotation.XmlType;

@XmlType(
        name = "ResourceUsageState",
        namespace = "com.nokia.nsw.uiv.model.resource"
)
public enum ResourceUsageState {
    Unknown,

    Available,

    Reserved,

    Assigned,

    NotAvailable
}
