// This source file was generated by Unified Inventory CodeGen, Please DO NOT modify this file.
package com.nokia.nsw.uiv.model.resource;

import com.fasterxml.jackson.annotation.JsonFilter;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonView;
import com.nokia.nsw.uiv.datatype.UivDatatypeObject;
import com.nokia.nsw.uiv.jackson.UivJsonViews;

@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        defaultImpl = com.nokia.nsw.uiv.model.resource.Software.class,
        include = JsonTypeInfo.As.EXISTING_PROPERTY,
        visible = true,
        property = "@type"
)
@JsonFilter("com.nokia.nsw.uiv.model.resource.Software")
public class Software extends UivDatatypeObject {
    @JsonView({
            UivJsonViews.WriteView.class,
            UivJsonViews.ReadView.class
    })
    private String name;

    @JsonView({
            UivJsonViews.WriteView.class,
            UivJsonViews.ReadView.class
    })
    private String version;

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        if ((name==null && this.name!=null) || (name != null && !name.equals(this.name))) {
            this.setModified(true);
        }
        this.name=name;
    }

    public String getVersion() {
        return this.version;
    }

    public void setVersion(String version) {
        if ((version==null && this.version!=null) || (version != null && !version.equals(this.version))) {
            this.setModified(true);
        }
        this.version=version;
    }
}
