// This source file was generated by Unified Inventory CodeGen, Please DO NOT modify this file.
package com.nokia.nsw.uiv.model.resource;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import org.neo4j.ogm.typeconversion.CompositeAttributeConverter;

public class SoftwareConverter implements CompositeAttributeConverter<Software> {
    @Override
    public Map<String, ?> toGraphProperties(Software value) {
        if (value == null) {
            return Collections.emptyMap();
        }
        Map<String, Object> properties = new HashMap<>();
        properties.put("software.name", value.getName());
        properties.put("software.version", value.getVersion());
        return properties;
    }

    @Override
    public Software toEntityAttribute(Map<String, ?> value) {
        if (value == null || value.isEmpty()) {
            return null;
        }
        if ( value.get("software.name") == null && value.get("software.version") == null ) {
            return null;
        }
        Software software = new Software();
        software.setName((String) value.get("software.name"));
        software.setVersion((String) value.get("software.version"));
        software.setModified(false);
        return software;
    }
}
