// This source file was generated by Unified Inventory CodeGen, Please DO NOT modify this file.
package com.nokia.nsw.uiv.model.common;

import javax.xml.bind.annotation.XmlType;

@XmlType(
        name = "com.nokia.nsw.uiv.model.common.AlarmSeverity"
)
public enum AlarmSeverity {
    Cleared,

    Indeterminate,

    Warning,

    Minor,

    Major,

    Critical
}
