// This source file was generated by Unified Inventory CodeGen, Please DO NOT modify this file.
package com.nokia.nsw.uiv.model.common;

import jakarta.xml.bind.annotation.XmlType;

@XmlType(
        name = "ProtectionAssociationType",
        namespace = "com.nokia.nsw.uiv.model.common"
)
public enum ProtectionAssociationType {
    Anyof,

    OneOf,

    AllOf
}
