// This source file was generated by Unified Inventory CodeGen, Please DO NOT modify this file.
package com.nokia.nsw.uiv.model.common;

import com.fasterxml.jackson.annotation.JsonFilter;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonView;
import com.nokia.nsw.uiv.datatype.Neo4jDomainRelationshipObject;
import com.nokia.nsw.uiv.datatype.UivHashMap;
import com.nokia.nsw.uiv.jackson.UivJsonViews;
import com.nokia.nsw.uiv.model.resource.Resource;
import com.nokia.nsw.uiv.model.service.Service;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Pattern;
import java.util.Map;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.neo4j.ogm.annotation.EndNode;
import org.neo4j.ogm.annotation.Properties;
import org.neo4j.ogm.annotation.RelationshipEntity;
import org.neo4j.ogm.annotation.StartNode;
import org.neo4j.ogm.annotation.typeconversion.Convert;

@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        defaultImpl = com.nokia.nsw.uiv.model.common.USES_PROTECTED_SERVICE.class,
        include = JsonTypeInfo.As.EXISTING_PROPERTY,
        visible = true,
        property = "@type"
)
@JsonFilter("com.nokia.nsw.uiv.model.common.USES_PROTECTED_SERVICE")
@RelationshipEntity(
        type = "USES_PROTECTED"
)
public class USES_PROTECTED_SERVICE extends Neo4jDomainRelationshipObject {
    @JsonView({
            UivJsonViews.WriteView.class,
            UivJsonViews.ReadView.class
    })
    private String tags;

    @JsonView({
            UivJsonViews.WriteView.class,
            UivJsonViews.ReadView.class
    })
    private Integer index;

    @JsonView({
            UivJsonViews.WriteView.class,
            UivJsonViews.ReadView.class
    })
    private String channel;

    @JsonView({
            UivJsonViews.WriteView.class,
            UivJsonViews.ReadView.class
    })
    @Properties
    @Convert(USES_PROTECTED_SERVICEPropertiesConverter.class)
    private Map<String,Object> properties = new UivHashMap<>();

    @JsonView({
            UivJsonViews.WriteView.class,
            UivJsonViews.ReadView.class
    })
    @Pattern(
            regexp = "((([A-Za-z0-9]+)\\.)+[0-9]+)"
    )
    private String secondaryIndex;

    @StartNode
    @JsonFilter("service")
    @Schema(
            type = "com.nokia.nsw.uiv.model.service.Service",
            implementation = String.class,
            allowableValues = "{com.nokia.nsw.uiv.model.service.Service}"
    )
    private Service service;

    @EndNode
    @JsonFilter("resource")
    @Schema(
            type = "com.nokia.nsw.uiv.model.resource.Resource",
            implementation = String.class,
            allowableValues = "{com.nokia.nsw.uiv.model.resource.Resource}"
    )
    private Resource resource;

    public String getTags() {
        return this.tags;
    }

    public void setTags(String tags) {
        if ((tags==null && this.tags!=null) || (tags != null && !tags.equals(this.tags))) {
            this.setModified(true);
        }
        this.tags=tags;
    }

    public Integer getIndex() {
        return this.index;
    }

    public void setIndex(Integer index) {
        if ((index==null && this.index!=null) || (index != null && !index.equals(this.index))) {
            this.setModified(true);
        }
        this.index=index;
    }

    public String getChannel() {
        return this.channel;
    }

    public void setChannel(String channel) {
        if ((channel==null && this.channel!=null) || (channel != null && !channel.equals(this.channel))) {
            this.setModified(true);
        }
        this.channel=channel;
    }

    public Map<String, Object> getProperties() {
        return this.properties;
    }

    public void setProperties(Map<String, Object> properties) {
        if ((properties==null && this.properties!=null) || (properties != null && !properties.equals(this.properties))) {
            this.setModified(true);
        }
        if (this.properties != null && properties != null && !(properties instanceof UivHashMap)) {
            this.properties.putAll(properties);
        }
        this.properties=properties;
    }

    public String getSecondaryIndex() {
        return this.secondaryIndex;
    }

    public void setSecondaryIndex(String secondaryIndex) {
        if ((secondaryIndex==null && this.secondaryIndex!=null) || (secondaryIndex != null && !secondaryIndex.equals(this.secondaryIndex))) {
            this.setModified(true);
        }
        this.secondaryIndex=secondaryIndex;
    }

    @Override
    public boolean equals(Object otherObj) {
        if (this == otherObj) return true;
        if (!(otherObj instanceof USES_PROTECTED_SERVICE)) return false;
        USES_PROTECTED_SERVICE other = (USES_PROTECTED_SERVICE) otherObj;
        if (null != this.getUuid() && this.getUuid().equals(other.getUuid())) {
            return true;
        }
        return new EqualsBuilder().append(this.getService(), other.getService())
                .append(this.getResource(), other.getResource())
                .isEquals();
    }

    @Override
    public int hashCode() {
        if (null != this.getUuid()) {
            return new HashCodeBuilder(17, 37).append(this.getUuid()).toHashCode();
        }
        return new HashCodeBuilder(17,37).append(getService())
                .append(getResource())
                .toHashCode();
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this).append("tags", this.tags)
                .append("index", this.index)
                .append("channel", this.channel)
                .append("properties", this.properties)
                .append("secondaryIndex", this.secondaryIndex)
                .toString();
    }

    public Service getService() {
        return service;
    }

    public void setService(Service service) {
        this.service=service;
        this.setAssocModified(true);
    }

    public Resource getResource() {
        return resource;
    }

    public void setResource(Resource resource) {
        this.resource=resource;
        this.setAssocModified(true);
    }
}
