// This source file was generated by Unified Inventory CodeGen, Please DO NOT modify this file.
package com.nokia.nsw.uiv.model.common.party;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import org.neo4j.ogm.typeconversion.CompositeAttributeConverter;

public class ContactMediumConverter implements CompositeAttributeConverter<ContactMedium> {
    @Override
    public Map<String, ?> toGraphProperties(ContactMedium value) {
        if (value == null) {
            return Collections.emptyMap();
        }
        Map<String, Object> properties = new HashMap<>();
        properties.put("contactMedium.email", value.getEmail());
        properties.put("contactMedium.phoneNumber", value.getPhoneNumber());
        properties.put("contactMedium.nationalDestinationCode", value.getNationalDestinationCode());
        properties.put("contactMedium.countryCode", value.getCountryCode());
        return properties;
    }

    @Override
    public ContactMedium toEntityAttribute(Map<String, ?> value) {
        if (value == null || value.isEmpty()) {
            return null;
        }
        if ( value.get("contactMedium.email") == null && value.get("contactMedium.phoneNumber") == null && value.get("contactMedium.nationalDestinationCode") == null && value.get("contactMedium.countryCode") == null ) {
            return null;
        }
        ContactMedium contactMedium = new ContactMedium();
        contactMedium.setEmail((String) value.get("contactMedium.email"));
        contactMedium.setPhoneNumber((String) value.get("contactMedium.phoneNumber"));
        contactMedium.setNationalDestinationCode(value.get("contactMedium.nationalDestinationCode") == null ? null : ((Long) value.get("contactMedium.nationalDestinationCode")).intValue());
        contactMedium.setCountryCode(value.get("contactMedium.countryCode") == null ? null : ((Long) value.get("contactMedium.countryCode")).intValue());
        contactMedium.setModified(false);
        return contactMedium;
    }
}
