// This source file was generated by Unified Inventory CodeGen, Please DO NOT modify this file.
package com.nokia.nsw.uiv.model.common.party;

import com.fasterxml.jackson.annotation.JsonFilter;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonView;
import com.nokia.nsw.uiv.datatype.UivDatatypeObject;
import com.nokia.nsw.uiv.jackson.UivJsonViews;

@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        defaultImpl = com.nokia.nsw.uiv.model.common.party.ContactMedium.class,
        include = JsonTypeInfo.As.EXISTING_PROPERTY,
        visible = true,
        property = "@type"
)
@JsonFilter("com.nokia.nsw.uiv.model.common.party.ContactMedium")
public class ContactMedium extends UivDatatypeObject {
    @JsonView({
            UivJsonViews.WriteView.class,
            UivJsonViews.ReadView.class
    })
    private String email;

    @JsonView({
            UivJsonViews.WriteView.class,
            UivJsonViews.ReadView.class
    })
    private String phoneNumber;

    @JsonView({
            UivJsonViews.WriteView.class,
            UivJsonViews.ReadView.class
    })
    private Integer nationalDestinationCode;

    @JsonView({
            UivJsonViews.WriteView.class,
            UivJsonViews.ReadView.class
    })
    private Integer countryCode;

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        if ((email==null && this.email!=null) || (email != null && !email.equals(this.email))) {
            this.setModified(true);
        }
        this.email=email;
    }

    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        if ((phoneNumber==null && this.phoneNumber!=null) || (phoneNumber != null && !phoneNumber.equals(this.phoneNumber))) {
            this.setModified(true);
        }
        this.phoneNumber=phoneNumber;
    }

    public Integer getNationalDestinationCode() {
        return this.nationalDestinationCode;
    }

    public void setNationalDestinationCode(Integer nationalDestinationCode) {
        if ((nationalDestinationCode==null && this.nationalDestinationCode!=null) || (nationalDestinationCode != null && !nationalDestinationCode.equals(this.nationalDestinationCode))) {
            this.setModified(true);
        }
        this.nationalDestinationCode=nationalDestinationCode;
    }

    public Integer getCountryCode() {
        return this.countryCode;
    }

    public void setCountryCode(Integer countryCode) {
        if ((countryCode==null && this.countryCode!=null) || (countryCode != null && !countryCode.equals(this.countryCode))) {
            this.setModified(true);
        }
        this.countryCode=countryCode;
    }
}
