// This source file was generated by Unified Inventory CodeGen, Please DO NOT modify this file.
package com.nokia.nsw.uiv.model.resource.infra.virtual;

import com.fasterxml.jackson.annotation.JsonFilter;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonView;
import com.nokia.nsw.uiv.constants.FeatureFlag;
import com.nokia.nsw.uiv.datatype.SchemaSpecification;
import com.nokia.nsw.uiv.exception.ModificationNotAllowedException;
import com.nokia.nsw.uiv.framework.context.UivSpringContextAware;
import com.nokia.nsw.uiv.jackson.UivJsonViews;
import com.nokia.nsw.uiv.model.resource.infra.InfraDevice;
import javax.validation.Valid;
import javax.xml.bind.annotation.XmlType;
import lombok.extern.slf4j.Slf4j;
import org.neo4j.ogm.annotation.NodeEntity;
import org.neo4j.ogm.annotation.Transient;

@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        defaultImpl = com.nokia.nsw.uiv.model.resource.infra.virtual.VirtualDevice.class,
        include = JsonTypeInfo.As.EXISTING_PROPERTY,
        visible = true,
        property = "@type"
)
@JsonFilter("com.nokia.nsw.uiv.model.resource.infra.virtual.VirtualDevice")
@NodeEntity(
        label = "com.nokia.nsw.uiv.model.resource.infra.virtual.VirtualDevice"
)
@Slf4j
@XmlType(
        name = "com.nokia.nsw.uiv.model.resource.infra.virtual.VirtualDevice"
)
public class VirtualDevice extends InfraDevice {
    @JsonView(UivJsonViews.TmfView.class)
    @Transient
    @Valid
    private SchemaSpecification virtualDeviceSpecification;

    public SchemaSpecification getVirtualDeviceSpecification() {
        FeatureFlag featureFlag = UivSpringContextAware.getApplicationContext().getBean(FeatureFlag.class);
        if (this.getKind() != null && Boolean.parseBoolean(featureFlag.getTmfEnabled())) {
            this.virtualDeviceSpecification = new SchemaSpecification();
            this.virtualDeviceSpecification.setId(this.getKind());
            this.virtualDeviceSpecification.setName(this.getKind());
            this.virtualDeviceSpecification.setReferredType(this.getKind());
            this.virtualDeviceSpecification.setVersion(this.getSchemaVersion());
        }
        return this.virtualDeviceSpecification;
    }

    public void setVirtualDeviceSpecification(SchemaSpecification virtualDeviceSpecification) throws
            ModificationNotAllowedException {
        FeatureFlag featureFlag = UivSpringContextAware.getApplicationContext().getBean(FeatureFlag.class);
        if (Boolean.parseBoolean(featureFlag.getTmfEnabled())) {
            if (null != virtualDeviceSpecification && null != virtualDeviceSpecification.getId()) {
                if(null == this.getKind()) {
                    this.setSpecification(virtualDeviceSpecification);
                    this.setKind(virtualDeviceSpecification.getId());
                }
                else if (!this.getKind().equals(virtualDeviceSpecification.getId())) {
                    throw new ModificationNotAllowedException("virtualDeviceSpecification modification not allowed");
                }
            }
            this.virtualDeviceSpecification = virtualDeviceSpecification;
        }
    }
}
