// This source file was generated by Unified Inventory CodeGen, Please DO NOT modify this file.
package com.nokia.nsw.uiv.model.service;

import javax.xml.bind.annotation.XmlType;

@XmlType(
        name = "com.nokia.nsw.uiv.model.service.ServiceOperationalState"
)
public enum ServiceOperationalState {
    unknown,

    designed,

    active,

    inactive,

    terminated
}
