// This source file was generated by Unified Inventory CodeGen, Please DO NOT modify this file.
package com.nokia.nsw.uiv.model.service;

import jakarta.xml.bind.annotation.XmlType;

@XmlType(
        name = "ServiceOperationalState",
        namespace = "com.nokia.nsw.uiv.model.service"
)
public enum ServiceOperationalState {
    unknown,

    designed,

    active,

    inactive,

    terminated,

    reserved,

    feasibilityChecked
}
